version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK
  deploy-to-render-production:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Production
          command: |
            echo "Deploying to Render production"
            curl $RENDER_PRODUCTION_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging-then-production:
    jobs:
      - cypress/run:
          name: run-e2e-tests
          cypress-command: npx cypress run --browser electron --headless
          # Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
          start-command: npm run start:dev
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          requires:
            - run-e2e-tests
            - run-component-tests
          filters:
            branches:
              only: main
      - deploy-to-render-production:
          requires:
            - deploy-to-render-staging
          filters:
            branches:
              only: main
